# SPDX-FileCopyrightText: 2021 Daniel Laidig <laidig@control.tu-berlin.de>
#
# SPDX-License-Identifier: MIT

version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


formats:
   - pdf
